config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    member do
      put "like" => "posts#like"
    end
  end
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :password_confirmation])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  respond_to :js, :html, :json
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def like
    @post =Post.find(params[:id])
    if params[:format] == 'like'
      @post.liked_by current_user
    elsif params[:format] == 'unlike'
      @post.unliked_by current_user
    end
  end
  
  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Social Networking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

  </head>
  
  <body>
    <%= render 'partials/navbar' %></br></br></br>
    <div class = "container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Social Networking site", root_url, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="navbar-top">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to('Profile')%></li>
              <li><%= link_to 'Edit Profile'%></li>
              <li><%= link_to 'Change password', edit_user_registration_path %></li>
              <li><%= link_to('Sign out', destroy_user_session_path, method: :delete) %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'About' %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <li><%= link_to 'Sign in', user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>

  <tbody>
    <% @posts.each do |post| %>
      <p>
        <strong>Body:</strong>
        <%= post.body %>
      </p>

      <p>
        <strong>User:</strong>
        <%= post.user.name %>
      </p>
      <span class = "parent-likes">
        <span class = "like_count" <%= post.id %>'>
          <%= post.get_likes.size %> &#128591
        </span>

        <a>
          <% if current_user.liked?post %>
            <div><%= link_to like_post_path(post, 'unlike'), class: "preached-btn", method: :put,remote:true do %>
              Liked
            </div>
            <% end %>
          <% else %>
            <div> <%= link_to like_post_path(post, 'like'), class: "preached-btn", method: :put,remote:true do %>
              Like
            </div>
            <% end %>
          <% end %>
        <a>
      </span></br>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/like.js.erb
console.log("hii")
$('.preached_btn').on('ajax:sucess', function(){
    $(this).parent().find('.like_count')
    .html('<%= @post.get_likes.size %> &#128591');
    console.log(<%= @post.get_likes.size %>);
    $(this).closet('.preached_btn').html('Like');
});

$('.preached_btn').on('ajax:sucess', function(){
    $(this).parent().find('.like_count')
    .html('<%= @post.get_likes.size %> &#128591');
    $(this).closet('.preached_btn').html('Liked');
});

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.name %>
</p>
<span class = "parent-likes">
  <span class = "like_count" <%= @post.id %>'>
    <%= @post.get_likes.size %> &#128591
  </span>

  <a>
    <% if current_user.liked?@post %>
      <div><%= link_to like_post_path(@post, 'unlike'), class: "preached-btn", method: :put,remote:true do %>
        Liked
      </div>
      <% end %>
    <% else %>
      <div> <%= link_to like_post_path(@post, 'like'), class: "preached-btn", method: :put,remote:true do %>
        Like
      </div>
      <% end %>
    <% end %>
  <a>
</span>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>